# Generated by Django 3.1.7 on 2021-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='この項目は必須です。メールアドレスは公開されません。@ed.tmu.ac.jpのみ使用できます。', max_length=254, verbose_name='email address'),
        ),
    ]
