# Generated by Django 3.1.3 on 2020-12-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='科目種別')),
                ('no', models.CharField(blank=True, max_length=10, verbose_name='授業番号')),
                ('semester', models.CharField(blank=True, max_length=5, verbose_name='学期')),
                ('day', models.CharField(blank=True, max_length=1, verbose_name='曜日')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='科目')),
                ('period', models.CharField(blank=True, max_length=2, verbose_name='時限')),
                ('teacher', models.CharField(blank=True, max_length=30, verbose_name='担当教員')),
                ('credit', models.CharField(blank=True, max_length=1, verbose_name='単位')),
            ],
            options={
                'verbose_name': '授業',
                'verbose_name_plural': '授業一覧',
            },
        ),
    ]
