# Generated by Django 3.1.7 on 2021-04-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cissapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='time',
        ),
    ]
