# Generated by Django 3.1.3 on 2021-02-14 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cissapp', '0002_postmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=30, null=True, verbose_name='科目')),
                ('content', models.TextField(null=True, verbose_name='本文')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cissapp.data')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿一覧',
            },
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
