# Generated by Django 3.1.3 on 2021-02-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissapp', '0003_auto_20210214_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='本文'),
        ),
    ]
