# Generated by Django 3.1.3 on 2021-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissapp', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pub_flg',
            field=models.BooleanField(default=True),
        ),
    ]
