# Generated by Django 3.1.7 on 2021-04-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissapp', '0008_auto_20210406_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.CharField(blank=True, max_length=225, verbose_name='科目種別'),
        ),
        migrations.AlterField(
            model_name='data',
            name='credit',
            field=models.CharField(blank=True, max_length=225, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(blank=True, max_length=225, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='data',
            name='no',
            field=models.CharField(blank=True, max_length=225, verbose_name='授業番号'),
        ),
        migrations.AlterField(
            model_name='data',
            name='period',
            field=models.CharField(blank=True, max_length=225, verbose_name='時限'),
        ),
        migrations.AlterField(
            model_name='data',
            name='teacher',
            field=models.CharField(blank=True, max_length=225, verbose_name='担当教員'),
        ),
    ]
