# Generated by Django 3.1.3 on 2021-03-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic2',
            name='pub_flg',
            field=models.BooleanField(default=True),
        ),
    ]
